### ISSUE TITLE
Possibility to create Vault inside an already created VPC

### ISSUE THREAD

**Issue by dzirg44** [binlab/terraform-aws-vault-ha-raft#4]
it would be nice to have it in this module

**Comment by binlab** [comment]
Thanks, for reporting! 
One of the main goals of this module, as described [here](https://github.com/binlab/terraform-aws-vault-ha-raft#why) - Independence. The module is totally independent of other parts of the infrastructure and it’s not good to locking it to other parts by architectural reasons. Maybe for your approach better to use a [VPC Peering](https://aws.amazon.com/blogs/aws/new-vpc-peering-for-the-amazon-virtual-private-cloud/). 
Detailed instruction and the example you can find here: [VPC Peering different networks e.g. RDS Database](https://github.com/binlab/terraform-aws-vault-ha-raft/tree/master/examples/vpc-peering-rds)
Let me know if you have some objections

**Comment by dzirg44** [comment]
Thanks a lot for it! Looking forward to see it in next release!!!! The best Vault terraform module is getting better!
